// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXFTl6sDtx3SmjeDVEWwJL_l6MlWhi48',
    appId: '1:879734585335:web:2aec628fa7ec5c8ae220f2',
    messagingSenderId: '879734585335',
    projectId: 'tuwaiqcommunity',
    authDomain: 'tuwaiqcommunity.firebaseapp.com',
    storageBucket: 'tuwaiqcommunity.appspot.com',
    measurementId: 'G-XN99FGGNQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrG5FyeNO5sfnDnJn4tNKbtGX2mFeYjE',
    appId: '1:879734585335:android:e851c7ad19fb5560e220f2',
    messagingSenderId: '879734585335',
    projectId: 'tuwaiqcommunity',
    storageBucket: 'tuwaiqcommunity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIIZCIJymlEXNI4070XmU_TyvieAaVZss',
    appId: '1:879734585335:ios:e9815f82ef9058c8e220f2',
    messagingSenderId: '879734585335',
    projectId: 'tuwaiqcommunity',
    storageBucket: 'tuwaiqcommunity.appspot.com',
    iosClientId: '879734585335-u56v3rhg6ad5m7c1ll79ur1isqk9s1or.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuwaiqCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIIZCIJymlEXNI4070XmU_TyvieAaVZss',
    appId: '1:879734585335:ios:e9815f82ef9058c8e220f2',
    messagingSenderId: '879734585335',
    projectId: 'tuwaiqcommunity',
    storageBucket: 'tuwaiqcommunity.appspot.com',
    iosClientId: '879734585335-u56v3rhg6ad5m7c1ll79ur1isqk9s1or.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuwaiqCommunity',
  );
}
